#!/bin/sh
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" = "master" ] || [ "$current_branch" = "main" ]; then
  echo "Direct push to master/main is not allowed. Please use PR."
  exit 1
fi
# Add full test suite execution here
